from __future__ import annotations
import os

def _flag(name: str, default: str = "false") -> bool:
    return os.getenv(name, default).strip().lower() in {"1", "true", "yes", "on"}

AI_BRIDGE_ORCHESTRATION_BACKEND = os.getenv("AI_BRIDGE_ORCHESTRATION_BACKEND", "native")
AI_BRIDGE_SCHEDULER_BACKEND = os.getenv("AI_BRIDGE_SCHEDULER_BACKEND", "local")
AI_BRIDGE_STATE_BACKEND = os.getenv("AI_BRIDGE_STATE_BACKEND", "memory")
AI_BRIDGE_MEMORY_BACKEND = os.getenv("AI_BRIDGE_MEMORY_BACKEND", "existing")
AI_BRIDGE_EVENT_BUS = os.getenv("AI_BRIDGE_EVENT_BUS", "local")
AI_BRIDGE_MODEL_ROUTER = os.getenv("AI_BRIDGE_MODEL_ROUTER", "native")
AI_BRIDGE_CONTEXT_MANAGER = os.getenv("AI_BRIDGE_CONTEXT_MANAGER", "native")
AI_BRIDGE_PROMPT_PROCESSOR = os.getenv("AI_BRIDGE_PROMPT_PROCESSOR", "native")

AI_BRIDGE_ENABLE_POSTGRES_STATE = _flag("AI_BRIDGE_ENABLE_POSTGRES_STATE")
AI_BRIDGE_ENABLE_REDIS = _flag("AI_BRIDGE_ENABLE_REDIS")
AI_BRIDGE_ENABLE_APSCHEDULER = _flag("AI_BRIDGE_ENABLE_APSCHEDULER")
AI_BRIDGE_ENABLE_LANGGRAPH = _flag("AI_BRIDGE_ENABLE_LANGGRAPH")
AI_BRIDGE_ENABLE_TEMPORAL = _flag("AI_BRIDGE_ENABLE_TEMPORAL")
AI_BRIDGE_ENABLE_PLUGINS = _flag("AI_BRIDGE_ENABLE_PLUGINS")
AI_BRIDGE_ENABLE_SANDBOX = _flag("AI_BRIDGE_ENABLE_SANDBOX")
AI_BRIDGE_ENABLE_LITELLM = _flag("AI_BRIDGE_ENABLE_LITELLM")
AI_BRIDGE_ENABLE_INSTRUCTOR = _flag("AI_BRIDGE_ENABLE_INSTRUCTOR")
