
from typing import Any, Dict
from .base_agent import BaseAgent
from core.core.integrations.design_learning_module import DesignLearningModule
from core.core.session_memory import SessionMemory

class DesignAgent(BaseAgent):
    """
    Agent responsible for generating unique UI/UX design specifications 
    incorporating stochastic 'design noise' to prevent repetitive templates.
    """
    
    def __init__(self, memory: SessionMemory):
        super().__init__("design_agent")
        self.design_learning = DesignLearningModule(memory)

    def perform_task(self, task_type: str, task_context: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == "generate_design_spec":
            framework = task_context.get("framework", "react")
            design_direction = self.design_learning.suggest_ui_direction(framework)
            
            # The design direction already contains the 'noise' parameter
            # generated by DesignNoiseGenerator within DesignLearningModule
            
            return {
                "status": "success",
                "design_spec": design_direction
            }
        return {"status": "error", "message": f"Unsupported task type: {task_type}"}
