# master-config.conf
wal_level = replica
max_wal_senders = 10
wal_keep_size = 64MB
hot_standby = on
archive_mode = on
archive_command = 'test ! -f /var/lib/postgresql/data/archive/%f && cp %p /var/lib/postgresql/data/archive/%f'
