import Redis from "ioredis";
import { Project } from "ts-morph";
import * as dotenv from "dotenv";

dotenv.config();

const redis = new Redis(process.env.REDIS_URL || "redis://localhost:6379");
const project = new Project({
  tsConfigFilePath: process.env.TS_CONFIG_PATH || "../../../frontend-react/tsconfig.json",
});

async function handleFrontendTask(task: any) {
  console.log(`[Frontend] Handling task: ${task.task_id}`);
  
  // 1. AI Logic would go here (using middleware)
  const generatedCode = `
import React from 'react';

export const GeneratedComponent = () => {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-xl font-bold text-gray-800">Generated by AI Agent</h2>
      <p className="mt-2 text-gray-600">This component was created using ts-morph and Tailwind CSS.</p>
    </div>
  );
};
  `;

  // 2. Safe Write using ts-morph
  const filePath = `../../../frontend-react/src/components/${task.input.componentName || 'GeneratedComponent'}.tsx`;
  const sourceFile = project.createSourceFile(filePath, generatedCode, { overwrite: true });
  
  const diagnostics = sourceFile.getPreEmitDiagnostics();
  if (diagnostics.length > 0) {
    return { status: "failed", errors: ["Syntax error in generated code"] };
  }

  await sourceFile.save();
  return { status: "done", output: { summary: `Created component at ${filePath}` } };
}

async function startWorker() {
  console.log("Frontend Worker started...");
  while (true) {
    const res = await redis.blpop("queue:frontend", 0);
    if (res) {
      const [_, data] = res;
      const task = JSON.parse(data);
      try {
        const result = await handleFrontendTask(task);
        await redis.rpush(`result:${task.task_id}`, JSON.stringify(result));
      } catch (err: any) {
        await redis.rpush(`result:${task.task_id}`, JSON.stringify({ status: "failed", errors: [err.message] }));
      }
    }
  }
}

startWorker();
