from __future__ import annotations
from typing import Protocol, Any, Callable
class EventBus(Protocol):
    def publish(self, topic: str, payload: dict[str, Any]) -> None: ...
    def subscribe(self, topic: str, handler: Callable[[dict[str, Any]], None]) -> None: ...
