from __future__ import annotations
from typing import Protocol, Any
class MemoryStore(Protocol):
    def get(self, scope: str, owner_id: str, key: str) -> Any: ...
    def set(self, scope: str, owner_id: str, key: str, value: Any) -> None: ...
