from __future__ import annotations
from typing import Protocol, Any
class SchedulerBackend(Protocol):
    def schedule_task(self, task: Any) -> dict[str, Any]: ...
    def enqueue_retry(self, task: Any, reason: str) -> None: ...
