from __future__ import annotations
from typing import Protocol
class TokenBudgetManager(Protocol):
    def estimate(self, text: str) -> int: ...
    def can_fit(self, model: str, input_tokens: int, reserved_output_tokens: int = 1024) -> bool: ...
