from __future__ import annotations
from typing import Protocol, Any
class WorkflowStateStore(Protocol):
    def save_workflow(self, workflow_id: str, state: dict[str, Any]) -> None: ...
    def append_event(self, workflow_id: str, event_type: str, payload: dict[str, Any]) -> None: ...
    def get_workflow(self, workflow_id: str) -> dict[str, Any] | None: ...
